insert into address (address, postal_code, city, country, record_date) values ('849 Del Mar Junction', null, 'Hebian', 'China', '2022-03-27');
insert into address (address, postal_code, city, country, record_date) values ('59402 Erie Plaza', null, 'Fenjie', 'China', '2021-08-16');
insert into address (address, postal_code, city, country, record_date) values ('5136 4th Pass', '4174', 'Niederwaldkirchen', 'Austria', '2021-08-21');
insert into address (address, postal_code, city, country, record_date) values ('89 Ruskin Center', null, 'Wu’erqihan', 'China', '2021-08-11');
insert into address (address, postal_code, city, country, record_date) values ('03202 Springview Junction', null, 'Shamakhi', 'Azerbaijan', '2021-06-29');
insert into address (address, postal_code, city, country, record_date) values ('42794 Brentwood Lane', '7534', 'Enschede', 'Netherlands', '2021-04-18');
insert into address (address, postal_code, city, country, record_date) values ('67 Banding Trail', null, 'Sibanicú', 'Cuba', '2022-03-12');
insert into address (address, postal_code, city, country, record_date) values ('0249 Becker Terrace', '86-230', 'Lisewo', 'Poland', '2021-10-21');
insert into address (address, postal_code, city, country, record_date) values ('35 Orin Park', null, 'Belanting', 'Indonesia', '2022-01-27');
insert into address (address, postal_code, city, country, record_date) values ('5310 Montana Point', '92660 CEDEX', 'Boulogne-Billancourt', 'France', '2021-06-15');
insert into address (address, postal_code, city, country, record_date) values ('70 Superior Drive', '06300-000', 'Carapicuíba', 'Brazil', '2022-01-15');
insert into address (address, postal_code, city, country, record_date) values ('364 Longview Parkway', '307442', 'Korenëvo', 'Russia', '2021-09-06');
insert into address (address, postal_code, city, country, record_date) values ('1050 Dakota Street', null, 'Xiaogang', 'China', '2021-07-27');
insert into address (address, postal_code, city, country, record_date) values ('8 New Castle Way', '30509', 'Belisario Dominguez', 'Mexico', '2021-11-11');
insert into address (address, postal_code, city, country, record_date) values ('4 Coolidge Plaza', '4207', 'San Nicolas', 'Philippines', '2021-06-26');
insert into address (address, postal_code, city, country, record_date) values ('306 Bartillon Drive', '21005', 'San Cristóbal Verapaz', 'Guatemala', '2022-01-03');
insert into address (address, postal_code, city, country, record_date) values ('22 Northridge Center', '03203', 'Elx/Elche', 'Spain', '2021-04-18');
insert into address (address, postal_code, city, country, record_date) values ('59 Ridge Oak Center', '22010', 'Jerez', 'Guatemala', '2022-04-02');
insert into address (address, postal_code, city, country, record_date) values ('21 Kropf Alley', null, 'Onokivtsi', 'Ukraine', '2021-10-08');
insert into address (address, postal_code, city, country, record_date) values ('9 Weeping Birch Avenue', '5050-223', 'Peso da Régua', 'Portugal', '2021-08-24');
insert into address (address, postal_code, city, country, record_date) values ('3569 Clyde Gallagher Pass', '46-090', 'Popielów', 'Poland', '2021-12-12');
insert into address (address, postal_code, city, country, record_date) values ('9202 Fisk Alley', null, 'Tomé', 'Chile', '2021-05-28');
insert into address (address, postal_code, city, country, record_date) values ('5397 Utah Avenue', '242750', 'Dubrovka', 'Russia', '2021-08-15');
insert into address (address, postal_code, city, country, record_date) values ('54412 Ronald Regan Drive', null, 'Belize City', 'Belize', '2021-08-06');
insert into address (address, postal_code, city, country, record_date) values ('900 Armistice Pass', null, 'Hongkeli', 'China', '2021-05-19');
insert into address (address, postal_code, city, country, record_date) values ('7566 Melrose Plaza', '64-915', 'Jastrowie', 'Poland', '2021-07-12');
insert into address (address, postal_code, city, country, record_date) values ('2251 Elka Lane', null, 'Baiyangwan', 'China', '2022-03-11');
insert into address (address, postal_code, city, country, record_date) values ('62 Farwell Trail', null, 'Xialaxiu', 'China', '2021-08-31');
insert into address (address, postal_code, city, country, record_date) values ('445 Farwell Pass', null, 'Kuangsan', 'Indonesia', '2022-03-01');
insert into address (address, postal_code, city, country, record_date) values ('2138 Ridge Oak Way', null, 'Azor', 'Israel', '2022-01-07');
insert into address (address, postal_code, city, country, record_date) values ('106 Miller Alley', null, 'Cibunar', 'Indonesia', '2021-12-25');
insert into address (address, postal_code, city, country, record_date) values ('89864 Arkansas Avenue', '37404 CEDEX', 'Amboise', 'France', '2022-01-10');
insert into address (address, postal_code, city, country, record_date) values ('72557 Roth Alley', null, 'Rongxi', 'China', '2021-12-20');
insert into address (address, postal_code, city, country, record_date) values ('9 Hazelcrest Street', null, 'Wutongkou', 'China', '2021-06-24');
insert into address (address, postal_code, city, country, record_date) values ('2 Anhalt Trail', null, 'Kajansi', 'Uganda', '2022-03-17');
insert into address (address, postal_code, city, country, record_date) values ('70 Roxbury Pass', null, 'Portobelo', 'Panama', '2021-06-07');
insert into address (address, postal_code, city, country, record_date) values ('861 Express Junction', null, 'Bryukhovychi', 'Ukraine', '2022-01-16');
insert into address (address, postal_code, city, country, record_date) values ('40373 Kim Plaza', '3252', 'Byala Slatina', 'Bulgaria', '2022-03-24');
insert into address (address, postal_code, city, country, record_date) values ('4083 Crowley Pass', null, 'Shancheng', 'China', '2021-11-07');
insert into address (address, postal_code, city, country, record_date) values ('42054 Northport Alley', '79405', 'Lubbock', 'United States', '2021-08-05');
insert into address (address, postal_code, city, country, record_date) values ('8 Upham Terrace', '10298', 'Jablanovec', 'Croatia', '2021-07-17');
insert into address (address, postal_code, city, country, record_date) values ('426 Grim Center', 'G9T', 'Rayside-Balfour', 'Canada', '2022-04-12');
insert into address (address, postal_code, city, country, record_date) values ('21840 Fordem Hill', null, 'Dzvinogrud', 'Ukraine', '2022-03-13');
insert into address (address, postal_code, city, country, record_date) values ('807 Vahlen Plaza', null, 'Narowlya', 'Belarus', '2021-07-03');
insert into address (address, postal_code, city, country, record_date) values ('93794 Linden Pass', null, 'Haikou', 'China', '2021-06-07');
insert into address (address, postal_code, city, country, record_date) values ('52 Harbort Alley', '368160', 'Zandak', 'Russia', '2021-05-19');
insert into address (address, postal_code, city, country, record_date) values ('8666 Bowman Center', null, 'Kokkári', 'Greece', '2021-07-12');
insert into address (address, postal_code, city, country, record_date) values ('12 Manley Lane', null, 'Huaniao', 'China', '2021-08-22');
insert into address (address, postal_code, city, country, record_date) values ('18086 Eastwood Pass', null, 'Shencun', 'China', '2021-10-16');
insert into address (address, postal_code, city, country, record_date) values ('3224 Corry Avenue', '26-242', 'Ruda Maleniecka', 'Poland', '2022-03-30');
